mamabirthday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('wishes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishes/urls.py
from django.urls import path

from . import views

app_name = "wishes"
urlpatterns = [

    path('', views.index, name='index'),
    path('wishes/', views.detail, name='detail_no_id'),
    path('wishes/<int:wish_id>/', views.detail, name='detail'),

]

wishes/models.py
from django.db import models



class Wish(models.Model):

    wish_text = models.TextField(blank=True,null=True,default=None)

    sender = models.CharField(max_length=200)

    pub_date = models.DateTimeField('date published')

    image = models.ImageField(blank=True,null=True,default=None)

    audio = models.FileField(blank=True, null=True,default=None)

    video = models.FileField(blank=True, null=True,default=None)


    def __str__(self):
        return str(self.sender)
    class Meta:
        verbose_name_plural = 'Wishes'

wishes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader

from .models import Wish

def index(request):
    wish_count = Wish.objects.count() #pyright: ignore
    context = {'wish_count': wish_count}
    return render(request, 'wishes/index.html', context)

def detail(request, wish_id = None):
    if wish_id == None:
        cur_wish = Wish.objects.last()                    # pyright: ignore
    else:
        cur_wish = get_object_or_404(Wish, id=wish_id)

    prev_wish = Wish.objects .filter(pub_date__lt=cur_wish.pub_date).order_by('pub_date').last()# pyright: ignore
    next_wish = Wish.objects.filter(pub_date__gt=cur_wish.pub_date).order_by('pub_date').first()# pyright: ignore

    prev_id = prev_wish.id if prev_wish else None
    next_id = next_wish.id if next_wish else None

    context = {'cur_wish': cur_wish, 'prev_id': prev_id, 'next_id': next_id}
    return render(request, 'wishes/detail.html', context)

wishes/templates/wishes/detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{{cur_wish.sender}}</title>
		{% load static %}
		<link rel="stylesheet" href="{% static 'wishes/detail.css' %}">

	</head>
	<body>
		<header>
		<h1>Отправитель: {{cur_wish.sender}}</h1>
		</header>

		{% if cur_wish.image %}
			<img src="{{cur_wish.image.url}}" alt="Image">
		{% endif%}

                {% if cur_wish.wish_text %}
			<div id='wish_text'>
				{{cur_wish.wish_text}}
			</div>
                {% endif%}



		{%if cur_wish.audio%}
		 		<div id='voice'>голосовое сообщение:</div>
				<audio controls>
					<source src='{{cur_wish.audio.url}}' type='audio/mp3'>
					ur browser doesnt support this
				</audio>
		{% endif%}


		{%if cur_wish.video%}
			<video controls>
				<source src='{{cur_wish.video.url}}' type='video/mp4'>
				ur browser doesnt support this
			</video>
			{% endif%}

                <div id='navigation'>
			{% if next_id %}
				<a class='navbut' id='back' href="{% url 'wishes:detail' next_id %}">Назад</a>
			{%endif%}

			{% if prev_id%}
				<a class = 'navbut' id='next' href="{% url 'wishes:detail' prev_id %}">Далее</a>
			{%endif%}
		</div>

	</body>
</html>

wishes/templates/wishes/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>С днем рождения!</title>
    {% load static %}

     <link rel="stylesheet" href="{% static 'wishes/index.css' %}">
</head>
<body>
		<h1>С Днем Рождения!</h1>
    <h2>поздравлений к просмотру: {{ wish_count }}</h2>

    <a href="{% url 'wishes:detail_no_id' %}">перейти к поздравлениям</a>
</body>
</html>